//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  restaurant: Restaurant;
  restaurantConnection: RestaurantConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRestaurantArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRestaurantConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RestaurantFilter>;
};

export type DocumentFilter = {
  restaurant?: InputMaybe<RestaurantFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Restaurant | Folder;

export type Restaurant = Node & Document & {
  __typename?: 'Restaurant';
  name: Scalars['String']['output'];
  neighbourhood: Scalars['String']['output'];
  cuisine: Scalars['String']['output'];
  price: Scalars['String']['output'];
  address: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  website?: Maybe<Scalars['String']['output']>;
  mapsUrl?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  pick?: Maybe<Scalars['Boolean']['output']>;
  moods?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  dishes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  openDays?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RestaurantFilter = {
  name?: InputMaybe<StringFilter>;
  neighbourhood?: InputMaybe<StringFilter>;
  cuisine?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  website?: InputMaybe<StringFilter>;
  mapsUrl?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  pick?: InputMaybe<BooleanFilter>;
  moods?: InputMaybe<StringFilter>;
  dishes?: InputMaybe<StringFilter>;
  openDays?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type RestaurantConnectionEdges = {
  __typename?: 'RestaurantConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Restaurant>;
};

export type RestaurantConnection = Connection & {
  __typename?: 'RestaurantConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RestaurantConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateRestaurant: Restaurant;
  createRestaurant: Restaurant;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateRestaurantArgs = {
  relativePath: Scalars['String']['input'];
  params: RestaurantMutation;
};


export type MutationCreateRestaurantArgs = {
  relativePath: Scalars['String']['input'];
  params: RestaurantMutation;
};

export type DocumentUpdateMutation = {
  restaurant?: InputMaybe<RestaurantMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  restaurant?: InputMaybe<RestaurantMutation>;
};

export type RestaurantMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  neighbourhood?: InputMaybe<Scalars['String']['input']>;
  cuisine?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  website?: InputMaybe<Scalars['String']['input']>;
  mapsUrl?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  pick?: InputMaybe<Scalars['Boolean']['input']>;
  moods?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  dishes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  openDays?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type RestaurantPartsFragment = { __typename: 'Restaurant', name: string, neighbourhood: string, cuisine: string, price: string, address: string, summary?: string | null, website?: string | null, mapsUrl?: string | null, image?: string | null, pick?: boolean | null, moods?: Array<string | null> | null, dishes?: Array<string | null> | null, openDays?: Array<string | null> | null, body?: any | null };

export type RestaurantQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RestaurantQuery = { __typename?: 'Query', restaurant: { __typename: 'Restaurant', id: string, name: string, neighbourhood: string, cuisine: string, price: string, address: string, summary?: string | null, website?: string | null, mapsUrl?: string | null, image?: string | null, pick?: boolean | null, moods?: Array<string | null> | null, dishes?: Array<string | null> | null, openDays?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type RestaurantConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RestaurantFilter>;
}>;


export type RestaurantConnectionQuery = { __typename?: 'Query', restaurantConnection: { __typename?: 'RestaurantConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RestaurantConnectionEdges', cursor: string, node?: { __typename: 'Restaurant', id: string, name: string, neighbourhood: string, cuisine: string, price: string, address: string, summary?: string | null, website?: string | null, mapsUrl?: string | null, image?: string | null, pick?: boolean | null, moods?: Array<string | null> | null, dishes?: Array<string | null> | null, openDays?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const RestaurantPartsFragmentDoc = gql`
    fragment RestaurantParts on Restaurant {
  __typename
  name
  neighbourhood
  cuisine
  price
  address
  summary
  website
  mapsUrl
  image
  pick
  moods
  dishes
  openDays
  body
}
    `;
export const RestaurantDocument = gql`
    query restaurant($relativePath: String!) {
  restaurant(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RestaurantParts
  }
}
    ${RestaurantPartsFragmentDoc}`;
export const RestaurantConnectionDocument = gql`
    query restaurantConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RestaurantFilter) {
  restaurantConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RestaurantParts
      }
    }
  }
}
    ${RestaurantPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      restaurant(variables: RestaurantQueryVariables, options?: C): Promise<{data: RestaurantQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RestaurantQueryVariables, query: string}> {
        return requester<{data: RestaurantQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RestaurantQueryVariables, query: string}, RestaurantQueryVariables>(RestaurantDocument, variables, options);
      },
    restaurantConnection(variables?: RestaurantConnectionQueryVariables, options?: C): Promise<{data: RestaurantConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RestaurantConnectionQueryVariables, query: string}> {
        return requester<{data: RestaurantConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RestaurantConnectionQueryVariables, query: string}, RestaurantConnectionQueryVariables>(RestaurantConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/a01b4841-b4cf-4dc6-833b-32bd07c92e4a/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  